# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Francisco Alfaro Medina
site_url: https://github.com/fralfaro/portfolio
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/portfolio
repo_url: https://github.com/fralfaro/portfolio
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Theme
theme:
  name: material
  language: en
  logo: images/logo.bmp
  favicon: images/faam_logo.gif
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: amber
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/


 #TOC
nav:
    - Home:
      - index.md
      - Tech Stack:  about_me/stack.md
      - Certifications:  about_me/certification.md
      - Education:  about_me/education.md
      - Work Experience:  about_me/work_exp.md
      - Teaching Experience:  about_me/teaching_exp.md
      - Honors & awards:  about_me/awards.md
    - Activity:
      - Research: research/research.md
      - Talks: research/talks.md
      - Students: research/students.md
    - Software:
      - Python Packages: software/software.md
      - Collaboration: software/collaboration.md
      - Books: software/book.md
    - Teaching:
      - University Courses: teaching/universities.md
      - Personal  Courses: teaching/personal.md
    - Blog:
      - 2022: blog/2022.md
      - 2021: blog/2021.md
