# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Francisco Alfaro Medina
site_url: https://github.com/fralfaro/portfolio
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/portfolio
repo_url: https://github.com/fralfaro/portfolio
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects

extra_css:
  - css/neoteroi-mkdocs.css

# Theme
theme:
  name: dracula
  language: en
  logo: images/yo2.png
  favicon: images/logo_fam.png


# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

 #TOC
nav:
    - Home: index.md
    - About Me:
      - Presentation: about_me/me.md
      - Tech Stack:  about_me/stack.md
      - Certifications:  about_me/certification.md
      - Education:  about_me/education.md
      - Work Experience:  about_me/work_exp.md
      - Teaching Experience:  about_me/teaching_exp.md
      - Honors & Awards:  about_me/awards.md
      - Volunteering:  about_me/volunteering.md
    - Activity:
      - Research: research/research.md
      - Talks: research/talks.md
      - Students: research/students.md
    - Software:
      - Books: software/book.md
      - Collaboration: software/collaboration.md
      - Projects: software/projects.md
      - Python Packages: software/software.md
    - Teaching:
      - University Courses: teaching/universities.md
      - Personal Courses: teaching/personal.md
    - Blog:
        - Posts: blog/posts.md






