# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/portfolio
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/portfolio
repo_url: https://github.com/fralfaro/portfolio
edit_uri: ''

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


# Theme
theme:
  name: material
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fralfaro/portfolio

 #TOC
nav:
    - Home: index.md
    - Activities:
      - Research: research/research.md
      - Talks: research/talks.md
    - Software:
      - Python Packages: software/software.md
      - Collaboration: software/collaboration.md
    - Teaching:
      - Universities Courses: teaching/universities.md
      - Personal  Courses: teaching/personal.md
    - Blog:
      - 2022: blog/2022.md
      - 2021: blog/2021.md
